name: jk_economy
version: '1.0-SNAPSHOT'
main: jiekie.EconomyPlugin
api-version: '1.20'
authors: [Jiekie]
description: 경제 플러그인
depend: [jk_nickname, PlaceholderAPI]
commands:
  돈:
    description: 돈 설정 명령어
    usage: /돈
    tab-completer: jiekie.completer.MoneyTabCompleter
  수표:
    description: 수표 발행 명령어
    usage: /수표
    tab-completer: jiekie.completer.CheckTabCompleter
  상점:
    description: 상점 설정 명령어
    usage: /상점
    tab-completer: jiekie.completer.ShopTabCompleter
    permission: jk.shop.command
    permission-message: ''
